language: python
python:
  - "3.5"
install:
  - pip install coverage virtualenv
  - pip install coveralls
  - pip install -r requirments.txt
script:
  - tox
  - coverage run --source=downloader  --rcfile=.coveragerc setup.py test -s tests
after_success:
  - bash <(curl -s https://codecov.io/bash && coveralls)
notifications:
  email:
    on_failure: change
sudo: false
